#!/usr/bin/env bash

IMAGE_NAME=bitbots-melodic

# Build the docker image
buildah build-using-dockerfile \
	--network=host \
	--build-arg user=$USER \
	--build-arg home=$HOME \
	--build-arg workspace=$HOME \
	--build-arg shell=$SHELL \
	-t $IMAGE_NAME \
	$@ \
	$(dirname $0)

