#!/usr/bin/env bash
set -e

IMAGE_NAME=bitbots-melodic
CONTAINER_NAME=`podman ps --filter status=running --filter ancestor=$IMAGE_NAME --format "{{.Names}}"`

if [[ -z $CONTAINER_NAME ]]; then
    echo "Container not running, starting it"
    DIR=`dirname $0`
    bash -c "$DIR/start"
fi

CONTAINER_NAME=`podman ps --filter status=running --filter ancestor=$IMAGE_NAME --format "{{.Names}}"`

if [[ -z $@ ]]; then
	podman exec --privileged --user 0:0 -it $CONTAINER_NAME $SHELL
else
	podman exec --privileged --user 0:0 -t $CONTAINER_NAME "$@"
fi

