#!/usr/bin/env bash

IMAGE_NAME=bitbots-melodic
VIDEO_DEVICE=/dev/video0
# Get the group number of the video group, docker groups may differ
UUCP_GROUP=`cat /etc/group | grep uucp | cut -d : -f 3`

# Test whether a running container exists
CONTAINER_NAME=`podman ps --filter status=running --filter ancestor=$IMAGE_NAME --format "{{.Names}}"`
if [[ -n $CONTAINER_NAME ]]; then
    echo "Container already running, connect with ./connect or stop it with ./stop"
    exit 1
fi

# Test whether a stopped container exists
CONTAINER_NAME=`podman ps -a --filter status=exited --filter ancestor=$IMAGE_NAME --format "{{.Names}}"`
if [[ -n $CONTAINER_NAME ]]; then
	echo "Resuming stopped container"
	podman start $CONTAINER_NAME > /dev/null
else
	# Run the container with shared X11
	podman run \
	  -d \
	  --privileged \
	  --user 0:0 \
	  --net=host \
	  --add-host=$HOSTNAME:127.0.1.1 \
	  -e SHELL \
	  -e DISPLAY \
	  -e DOCKER=1 \
	  -v "/tmp/.X11-unix:/tmp/.X11-unix:rw" \
	  -v "/opt/pycharm-professional:/opt/pycharm-professional:ro" \
	  -v "/opt/clion:/opt/clion:ro" \
	  --mount type=bind,src=$HOME,target=$HOME \
	  --group-add=$UUCP_GROUP \
	  --name "rosdocked_melodic" \
	  $@ \
	  -it $IMAGE_NAME
fi

