#!/usr/bin/env bash

IMAGE_NAME=bitbots-melodic
CONTAINER_NAME=`podman ps -a --filter status=running --filter ancestor=$IMAGE_NAME --format "{{.Names}}"`

if [[ -z $CONTAINER_NAME ]]; then
    echo "The container is not running"
else
	echo "Stopping container"
    podman stop $CONTAINER_NAME > /dev/null  # Do not print container name
fi
